version: '3'

services:
    app:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: mj-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ../:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - mj-network

    nginx:
        image: nginx:alpine
        container_name: mj-nginx
        restart: unless-stopped
        ports:
            - "89:80"
        volumes:
            - ../:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - mj-network
        depends_on:
            - app

networks:
    mj-network:
        driver: bridge
